
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "pisandelli"
    versioning-strategy: increase